matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: gWr9VPAqYbI7AEolcCoK+3aRBKEZC5ZQDlTGmgqXATufjOLG604X4xBUb7RQeRX5KW6SPaNz9pwi/alGlLNd3D5ZmE5zMbqGnUKpxykIM/twk+LOikQRZbey8bEQSg7L8ecVLXnhuakpIgMsNk/Pw+mfImZZ7nlpDf3iZ5hNnFxt3VASuQXNk6AOcbvldeNpThlc75mjH8uki/xPal6W0edOhUTwQwstgwp+No51rx8ne/DsLQs5mg7JvaaXQkXAG4vSwPfseCizrjVylYFZaK2aFogLnEjcrVKDCtdzAkwAK2RFVaJB1MBVMZlsTqjGyQm4MmaVlZlpEOl6LWUOAOkM/SF2pzFTbxNHoS64xKNl5goJ7o1WiDimw/PhxCSNClr2RDIAGJx9aQIaCICJeLxYDY/eq9NbkjBIYn8ztw5TqJ65XOxTnhqwEbqkE4jlxNd+J1wmyr8WYVpqWn+Ivi3nnS9BteLcojdM5i49UmLYIBO+EqRQrhSB91ILxlYw1fSptUs878djbTl/m6RNYuQn2oQXtClFPZCbenDg+1ZgMNsk8dZP/kQ9KmQwy5MOcFW/96k1h3ps3joKzvgXZ5+LlIW/eYal2ht7/hI6a9NWUvyg7f0I69f+rjr5l3Drr5bbDzymSU6pv8xGVFyB2CcjYlgbdLtaaNi+yYkqjTo=
