matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: Bj6f30VRMXtA71S9FjQHJk0SJiq6A6YUp8dz/7w8M7CehLrSQGQL+0PxkznEOMx2aYr4LFMFZDHDUyETT3Bv6UbfTPFlJ1jHiKNTdGz+ic8Tw+Drmd5gnZcgVHJD+ifzWKtEON3mQlQLlI1QcNnOlUPEt1M3xvr+8ULOLP52WbkR72IIgCLTYm8f9+NAsRUY+kt3nmlRSj1oScRpuLradHSkXFDigzYkjmk+cQdlpEsbgBAZXT43BeVWuwTmfGbJ5gjkqc7nFTMLtIX6voHL7LzNv4nuUgRKlc4xqjYbPsWWB3Zz3FlNayeQHpR7/djt547Aho4SUshy23qnAyD5GXtHA6UCiJeL8zDKFILKE9uoTLKeN/0IT8xl2u5jwtS2bdkHK9g0ewYlxgzJrqU/nDc4I057PfEEB5gssmgayxh9umIFb+ZX1KLFiPgoLvT6a0aXpDbwiZ2cVwWNXj792Vt3NOI+7Ab2G4+CtCVq5y03AOk9ZlEGRICyhcuiT6OCkWUuU88XfIYzTIG2qL07htbvOFeMmE4/HO/hdCXgYr4kv9evDrP9XV4v3D4bi+aZhWYWu12zpW4oSomHDMiuYqaUMCZnlTAhPRWxHg8mzU9EBRBEfeqWEvHndFsuhaQ0GaBYFUjoRirI0Ig7rfdbsLgdJk+IyH813hCvR/q0pDM=
